# Generated by Django 5.1.5 on 2025-02-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defectsprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_id', models.CharField(max_length=100)),
                ('defect_name', models.CharField(max_length=100)),
                ('defect_type', models.CharField(max_length=100)),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=100)),
            ],
        ),
    ]
