# Generated by Django 5.1.5 on 2025-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defectsportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectsprofile',
            name='defect_type',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary'), ('TERTIARY', 'tertiary')], default='PRIMARY', max_length=100),
        ),
        migrations.AlterField(
            model_name='defectsprofile',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], default='HIGH', max_length=100),
        ),
    ]
