# Generated by Django 5.1.5 on 2025-02-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defectsportal', '0002_alter_defectsprofile_defect_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defects_screen_shots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_image', models.ImageField(blank=True, null=True, upload_to='defectsimg/')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect', to='defectsportal.defectsprofile')),
            ],
        ),
    ]
