# Generated by Django 5.1.5 on 2025-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defectsportal', '0003_defects_screen_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectsprofile',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('NOT COMPLETED', 'not completed')], default='COMPLETED', max_length=100),
        ),
    ]
