# Generated by Django 5.1.7 on 2025-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=500)),
                ('profile_img', models.ImageField(null=True, upload_to='student_profile_imgs/')),
            ],
            options={
                'verbose_name_plural': '5. Students',
            },
        ),
    ]
