# Generated by Django 5.1.7 on 2025-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_type',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
