# Generated by Django 5.1.5 on 2025-03-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Com',
            new_name='Company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
    ]
