# Generated by Django 5.1.5 on 2025-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindetails',
            name='ending_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traindetails',
            name='starting_from',
            field=models.CharField(max_length=100),
        ),
    ]
