# Generated by Django 5.1.5 on 2025-03-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_traindetails_ending_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traindetails',
            old_name='toatl_stops',
            new_name='total_stops',
        ),
    ]
