# Generated by Django 5.1.5 on 2025-03-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('seat_capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('Com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='cbvapp.company')),
            ],
        ),
    ]
