# Generated by Django 5.1.5 on 2025-02-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
