# Generated by Django 5.1.5 on 2025-03-03 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=100)),
                ('cmp_ceo', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_color', models.CharField(max_length=100)),
                ('fuletype', models.CharField(max_length=100)),
                ('seatcapasity', models.IntegerField()),
                ('cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmp', to='cbvapp.company')),
            ],
        ),
    ]
