# Generated by Django 5.1.5 on 2025-03-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='cbvapp.company'),
        ),
    ]
