# Generated by Django 5.1.5 on 2025-03-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0002_alter_product_cmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userimg/'),
        ),
    ]
