# Generated by Django 5.1.5 on 2025-03-07 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0003_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='productimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='productimg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cbvapp.product')),
            ],
        ),
    ]
