# Generated by Django 5.1.5 on 2025-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qnty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
